// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "pvz-service/internal/model"
)

// InfoService is an autogenerated mock type for the InfoService type
type InfoService struct {
	mock.Mock
}

// GetInfoPvz provides a mock function with given fields: ctx, query
func (_m *InfoService) GetInfoPvz(ctx context.Context, query *model.PvzInfoQuery) ([]*model.Pvz, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetInfoPvz")
	}

	var r0 []*model.Pvz
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.PvzInfoQuery) ([]*model.Pvz, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.PvzInfoQuery) []*model.Pvz); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Pvz)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.PvzInfoQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInfoService creates a new instance of InfoService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInfoService(t interface {
	mock.TestingT
	Cleanup(func())
}) *InfoService {
	mock := &InfoService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
